repositories:
  - name: datadog
    url: https://helm.datadoghq.com

releases:
  - name: datadog
    namespace: datadog
    labels:
      app: datadog
    chart: datadog/datadog
    version: 3.32.2
    values:
      - values.yaml
    secrets:
      - secrets.yaml