repositories:
  - name: datadog
    url: https://helm.datadoghq.com

releases:
  - name: datadog
    namespace: datadog
    labels:
      app: datadog
    chart: .
    # version: 3.33.0
    values:
      - values.yaml
    secrets:
      - secrets.yaml